# Generated by Django 4.0.5 on 2022-06-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='title_article',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
