# Generated by Django 4.0.5 on 2022-06-17 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_articlepage_title_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='categorys',
        ),
    ]
